name: Update Calendar

on:
  schedule:
    # Run on the 1st of every month at 9 AM UTC
    - cron: '0 9 1 * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Scrape and update calendar
        run: uv run scripts/update_calendar.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update Bandcamp Friday calendar
          file_pattern: bandcamp-friday.ics
